version: '3.8'

services:
  backend:
    build:
      context: ./vastuchitra-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - STABLE_DIFFUSION_API_KEY=${STABLE_DIFFUSION_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URL=http://frontend:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./vastuchitra-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
    depends_on:
      - backend
    restart: unless-stopped 