[build]
builder = "nixpacks"
buildCommand = "cd vastuchitra-backend && python -m pip install -r requirements.txt"

[deploy]
startCommand = "cd vastuchitra-backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python39", "nodejs"] 