[build]
builder = "nixpacks"
buildCommand = "pip install -r functions/src/backend/requirements.txt"

[deploy]
startCommand = "uvicorn functions.src.backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = "30s"

restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHONPATH = "/app"
PORT = "8000"

[phases.setup]
nixPkgs = ["python39"]