// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezfaavnkgpbgwvayikqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZmFhdm5rZ3BiZ3d2YXlpa3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTkyMDIsImV4cCI6MjA2MTQzNTIwMn0.1iwu6kva6UJycylCJju_i4x9JpDX0lSLoXsOf0prsJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);